config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  resources :games, only: %i[index create show update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  enum turn: %i[player_x player_o]
  enum status: %i[in_progress tie win_x win_o]

  def move
  end

  def play(input)
    position = input.to_i
    unless board[position - 1] == '.'
      errors.add(:board, 'invalid move, position already taken')
      return
    end

    if player_x?
      board[position - 1] = 'X'
      if winner?(position)
        self.status = :win_x
      elsif tie?
        self.status = :tie
      else
        self.turn = :player_o
      end
    else
      board[position - 1] = 'O'
      if winner?(position)
        self.status = :win_o
      elsif tie?
        self.status = :tie
      else
        self.turn = :player_x
      end
    end
    save!
  end

  private

  def tie?
    board.chars.exclude?('.')
  end

  def winner?(position)
    case position
    when 1
      row1? || col1? || diag1?
    when 2
      row1? || col2?
    when 3
      row1? || col3? || diag2?
    when 4
      row2? || col1?
    when 5
      row2? || col2? || diag1? || diag2?
    when 6
      row2? || col3?
    when 7
      row3? || col1? || diag2?
    when 8
      row3? || col2?
    when 9
      row3? || col3? || diag1?
    end
  end

  def row1?
    board[0] == board[1] && board[1] == board[2]
  end

  def row2?
    board[3] == board[4] && board[4] == board[5]
  end

  def row3?
    board[6] == board[7] && board[7] == board[8]
  end

  def col1?
    board[0] == board[3] && board[3] == board[6]
  end

  def col2?
    board[1] == board[4] && board[4] == board[7]
  end

  def col3?
    board[2] == board[5] && board[5] == board[8]
  end

  def diag1?
    board[0] == board[4] && board[4] == board[8]
  end

  def diag2?
    board[2] == board[4] && board[4] == board[6]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[show update destroy]

  # GET /games
  def index
    @games = Game.all
  end

  # GET /games/1
  def show
  end

  # POST /games
  def create
    @game = Game.new

    if @game.save
      redirect_to @game, notice: 'Game was successfully created.'
    else
      render :index
    end
  end

  def update
    @game.play(params[:game][:move])
    redirect_to @game, alert: @game.errors.first&.message
  end

  # DELETE /games/1
  def destroy
    @game.destroy
    redirect_to games_url, notice: 'Game was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_board.html.erb
<div style="font-family: courier">
  <div><%= game.board[0..2] %></div>
  <div><%= game.board[3..5] %></div>
  <div><%= game.board[6..8] %></div>
</div>

app/views/games/_instructions.html.erb
<p>Enter Position for <%= game.player_x? ? 'X' : 'O' %></p>
<p>
  <div>1 2 3</div>
  <div>4 5 6</div>
  <div>7 8 9</div>
</p>

app/views/games/_move.html.erb
<%= form_for @game do |form| %>
  <% if alert %>
    <div id="error_explanation">
      <%= alert %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :move %>
    <%= form.number_field :move, min: 1, max: 9 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Turn</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.turn %></td>
        <td><%= game.status %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', games_path, method: :post %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<% if @game.in_progress? %>

  <h1>Game <%= @game.id %></h1>

  <p>
    <%= render 'board', game: @game %>
    <%= render 'instructions', game: @game %>
    <%= render 'move', game: @game %>
  </p>

<% else %>

  <p>
    <strong>Status:</strong>
    <%= @game.status %>

    <%= render 'board', game: @game %>
  </p>

<% end %>

<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicTacToe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>